
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";

import Spinner from "./Components/Spinner";
import Image from "next/image";
import AuthProvider from "../../services/AuthProvider";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
 
  title: "MediPro",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <html lang="en" data-theme="light">

   <AuthProvider>
      <body className={inter.className}>
         
            <div>
            
            <Navbar></Navbar>
            {children}
            <Footer></Footer>
            
             </div>
         {/* } */}
        
         <Toaster></Toaster>
        </body>
        </AuthProvider>
        
    </html>
  );
}
